inherit_from: .rubocop_todo.yml

# This is the configuration used to check the rubocop source code.

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'

Metrics/BlockLength:
  Exclude:
    - 'app/admin/**/*'
