# config/redis.yml

default: &default
  host: 'localhost'
  port: '6379'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  host: <%= ENV.fetch("REDIS_HOST") %>
  port: <%= ENV.fetch("REDIS_PORT") %>
  username: <%= ENV.fetch("REDIS_USERNAME") %>
  password: <%= ENV.fetch("REDIS_PASSWORD") %>
  database: <%= ENV.fetch("REDIS_DATABASE") %>
  ssl: <%= ENV.fetch("REDIS_SSL") %>