development:
  :concurrency: 5

production:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 15 %>

:max_retries: 1

:queues:
  - [critical, 4]
  - [runners_notifiers, 3]
  - [kickers_notifiers, 2]
  - [default, 1]